/*
 * File:   event_types.h
 * Author: jason
 *
 * Created on September 26, 2015, 11:03 PM
 */

#ifndef EVENT_TYPES_H
#define	EVENT_TYPES_H

#define EVENT_TYPE_SPI "SPI"
#define EVENT_TYPE_GPIO "GPIO"
#define EVENT_TYPE_TIMER "TIMER"

#define EVENT_SPI_DRIVER_DETECTED       0x01

#define EVENT_SPI_DRIVER_DETECTED_NAME  "DRIVER_DETECTED"


/* GPIO Events use wiringPi pin numbers */
#define EVENT_GPIO_PEDAL_PRESSED        21
#define EVENT_GPIO_LEFT_TRIGGER         23
#define EVENT_GPIO_RIGHT_TRIGGER        22
#define EVENT_GPIO_ACCESSORY_ON         25

#define EVENT_GPIO_PEDAL_PRESSED_NAME   "PEDAL_PRESSED"
#define EVENT_GPIO_LEFT_TRIGGER_NAME    "LEFT_TRIGGER"
#define EVENT_GPIO_RIGHT_TRIGGER_NAME   "RIGHT_TRIGGER"
#define EVENT_GPIO_ACCESSORY_ON_NAME    "ACCESSORY_ON"

#endif	/* EVENT_TYPES_H */

