/*
 * File:   SoundTypes.h
 * Author: jason
 *
 * Created on September 30, 2015, 3:55 PM
 */

#ifndef SOUNDTYPES_H
#define	SOUNDTYPES_H

#define SOUND_TYPE_FOREGROUND   0x01
#define SOUND_TYPE_BACKGOUND    0x02
#define SOUND_TYPE_ALL          0x03

#define SOUND_TYPE_FOREGROUND_NAME  "FOREGROUND"
#define SOUND_TYPE_BACKGROUND_NAME  "BACKGROUND"
#define SOUND_TYPE_ALL_NAME         "ALL"

#define SOUND_REPEAT_NONE       0x00
#define SOUND_REPEAT_ONCE       0x01
#define SOUND_REPEAT_FOREVER    0xFF

#define SOUND_REPEAT_NONE_NAME      "NO_REPEAT"
#define SOUND_REPEAT_ONCE_NAME      "REPEAT_ONCE"
#define SOUND_REPEAT_FOREVER_NAME   "REPEAT_FOREVER"

#endif	/* SOUNDTYPES_H */

