/* 
 * File:   tievoxd.h
 * Author: jason
 *
 * Created on August 16, 2015, 9:22 PM
 */

#ifndef TIEVOXD_H
#define	TIEVOXD_H

/* Action Constants */
#define ACTION_TYPE_PLAY_SOUND "PLAY_SOUND"

/* Event Constants */
#define EVENT_TYPE_SPI "SPI"
#define EVENT_TYPE_GPIO "GPIO"
#define EVENT_TYPE_TIMER "TIMER"

#define EVENT_SPI_DRIVER_DETECTED       0x01

#define EVENT_SPI_DRIVER_DETECTED_NAME  "DRIVER_DETECTED"

/* GPIO Events use wiringPi pin numbers */
#define EVENT_GPIO_PEDAL_PRESSED        21
#define EVENT_GPIO_LEFT_TRIGGER         23
#define EVENT_GPIO_RIGHT_TRIGGER        22
#define EVENT_GPIO_ACCESSORY_ON         25

#define EVENT_GPIO_PEDAL_PRESSED_NAME   "PEDAL_PRESSED"
#define EVENT_GPIO_LEFT_TRIGGER_NAME    "LEFT_TRIGGER"
#define EVENT_GPIO_RIGHT_TRIGGER_NAME   "RIGHT_TRIGGER"
#define EVENT_GPIO_ACCESSORY_ON_NAME    "ACCESSORY_ON"

/* Sound Constants */
#define SOUND_TYPE_FOREGROUND   0x01
#define SOUND_TYPE_BACKGOUND    0x02
#define SOUND_TYPE_ALL          0x03

#define SOUND_TYPE_FOREGROUND_NAME  "FOREGROUND"
#define SOUND_TYPE_BACKGROUND_NAME  "BACKGROUND"
#define SOUND_TYPE_ALL_NAME         "ALL"

#define SOUND_REPEAT_NONE       0x00
#define SOUND_REPEAT_ONCE       0x01
#define SOUND_REPEAT_FOREVER    0xFF

#define SOUND_REPEAT_NONE_NAME      "NO_REPEAT"
#define SOUND_REPEAT_ONCE_NAME      "REPEAT_ONCE"
#define SOUND_REPEAT_FOREVER_NAME   "REPEAT_FOREVER"

#endif	/* TIEVOXD_H */

